-- ==============================================================================
-- FARM FATALE: Supabase Schema Migration 001_init.sql
-- Database Initialization for Multiplayer Asymmetric Survival Game
-- ==============================================================================

-- 1. Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Players Table (Matches existing user table: id BIGINT, user_id TEXT UNIQUE, username TEXT)
CREATE TABLE IF NOT EXISTS public.players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT UNIQUE NOT NULL,
    username TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    total_matches INTEGER NOT NULL DEFAULT 0,
    total_wins INTEGER NOT NULL DEFAULT 0,
    favorite_animal TEXT NOT NULL DEFAULT 'pig'
);

-- 3. Match History (Authoritative server writes upon round completion)
CREATE TABLE IF NOT EXISTS public.matches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    started_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    ended_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    winner TEXT NOT NULL CHECK (winner IN ('animals', 'butcher')),
    round_duration INTEGER NOT NULL DEFAULT 240,
    player_count INTEGER NOT NULL CHECK (player_count >= 1),
    bot_count INTEGER NOT NULL DEFAULT 0,
    altar_sacrifices INTEGER NOT NULL DEFAULT 0
);

-- 4. Match Players (Per-player round performance breakdown)
CREATE TABLE IF NOT EXISTS public.match_players (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    match_id UUID NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL,
    animal TEXT NOT NULL,
    mark_final INTEGER NOT NULL DEFAULT 0,
    score INTEGER NOT NULL DEFAULT 0,
    became_butcher BOOLEAN NOT NULL DEFAULT false,
    volunteered BOOLEAN NOT NULL DEFAULT false,
    kills INTEGER NOT NULL DEFAULT 0,
    survived BOOLEAN NOT NULL DEFAULT false,
    was_bot BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 5. Daily Leaderboard
CREATE TABLE IF NOT EXISTS public.leaderboard_daily (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    score INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_leaderboard_daily UNIQUE (profile_id, date)
);

-- 6. Weekly Leaderboard
CREATE TABLE IF NOT EXISTS public.leaderboard_weekly (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    week_start DATE NOT NULL,
    score INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_leaderboard_weekly UNIQUE (profile_id, week_start)
);

-- 7. Legendary Leaderboard (ELO rating with inactivity decay)
CREATE TABLE IF NOT EXISTS public.leaderboard_legendary (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE UNIQUE,
    rating INTEGER NOT NULL DEFAULT 1000,
    last_played TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 8. Cosmetics Catalog
CREATE TABLE IF NOT EXISTS public.cosmetics (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('skin', 'hat', 'trail', 'taunt')),
    animal TEXT, -- NULL denotes all animals, or 'chicken', 'pig', 'butcher', etc.
    description TEXT,
    icon_url TEXT,
    cost INTEGER NOT NULL DEFAULT 0,
    is_premium BOOLEAN NOT NULL DEFAULT false
);

-- 9. Player Inventory
CREATE TABLE IF NOT EXISTS public.inventory (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    cosmetic_id TEXT NOT NULL REFERENCES public.cosmetics(id) ON DELETE CASCADE,
    is_equipped BOOLEAN NOT NULL DEFAULT false,
    acquired_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT uq_profile_cosmetic UNIQUE (profile_id, cosmetic_id)
);

-- 10. Bot Configuration
CREATE TABLE IF NOT EXISTS public.bot_config (
    id TEXT PRIMARY KEY,
    difficulty TEXT NOT NULL DEFAULT 'normal',
    reaction_delay_ms INTEGER NOT NULL DEFAULT 300,
    wander_radius REAL NOT NULL DEFAULT 150.0,
    flee_distance REAL NOT NULL DEFAULT 220.0,
    stealth_affinity REAL NOT NULL DEFAULT 0.5,
    is_active BOOLEAN NOT NULL DEFAULT true
);

-- ==============================================================================
-- INDEXES
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_matches_started_at ON public.matches(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_match_players_match ON public.match_players(match_id);
CREATE INDEX IF NOT EXISTS idx_match_players_profile ON public.match_players(profile_id);
CREATE INDEX IF NOT EXISTS idx_leaderboard_daily_date_score ON public.leaderboard_daily(date, score DESC);
CREATE INDEX IF NOT EXISTS idx_leaderboard_weekly_week_score ON public.leaderboard_weekly(week_start, score DESC);
CREATE INDEX IF NOT EXISTS idx_leaderboard_legendary_rating ON public.leaderboard_legendary(rating DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_profile ON public.inventory(profile_id);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Rule: Public read for leaderboards, matches, cosmetics, profiles.
-- Game server writes via SERVICE ROLE KEY.
-- ==============================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaderboard_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaderboard_weekly ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaderboard_legendary ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cosmetics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bot_config ENABLE ROW LEVEL SECURITY;

-- Profiles: Public read, authenticated users can insert/update their own profile
CREATE POLICY "Public profiles read" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can create profile" ON public.profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id OR auth.uid() IS NULL);

-- Matches: Public read, Service Role write
CREATE POLICY "Public matches read" ON public.matches FOR SELECT USING (true);
CREATE POLICY "Service role match manage" ON public.matches FOR ALL USING (auth.role() = 'service_role');

-- Match Players: Public read, Service Role write
CREATE POLICY "Public match players read" ON public.match_players FOR SELECT USING (true);
CREATE POLICY "Service role match players manage" ON public.match_players FOR ALL USING (auth.role() = 'service_role');

-- Leaderboards: Public read, Service Role write
CREATE POLICY "Public daily read" ON public.leaderboard_daily FOR SELECT USING (true);
CREATE POLICY "Service role daily manage" ON public.leaderboard_daily FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Public weekly read" ON public.leaderboard_weekly FOR SELECT USING (true);
CREATE POLICY "Service role weekly manage" ON public.leaderboard_weekly FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Public legendary read" ON public.leaderboard_legendary FOR SELECT USING (true);
CREATE POLICY "Service role legendary manage" ON public.leaderboard_legendary FOR ALL USING (auth.role() = 'service_role');

-- Cosmetics: Public read
CREATE POLICY "Public cosmetics read" ON public.cosmetics FOR SELECT USING (true);
CREATE POLICY "Service role cosmetics manage" ON public.cosmetics FOR ALL USING (auth.role() = 'service_role');

-- Inventory: Owner read, Service role manage
CREATE POLICY "Users view own inventory" ON public.inventory FOR SELECT USING (auth.uid() = profile_id OR auth.uid() IS NULL);
CREATE POLICY "Service role inventory manage" ON public.inventory FOR ALL USING (auth.role() = 'service_role');

-- Bot Config: Public read
CREATE POLICY "Public bot config read" ON public.bot_config FOR SELECT USING (true);
CREATE POLICY "Service role bot config manage" ON public.bot_config FOR ALL USING (auth.role() = 'service_role');

-- ==============================================================================
-- INITIAL SEED DATA
-- ==============================================================================
INSERT INTO public.cosmetics (id, name, type, animal, description, cost, is_premium) VALUES
('hat_straw', 'Farmer Straw Hat', 'hat', NULL, 'Classic farmhand straw hat for sun protection.', 100, false),
('hat_cowboy', 'Outlaw Stetson', 'hat', NULL, 'A weathered leather cowboy hat.', 250, false),
('skin_butcher_golden', 'Gilded Cleaver Apron', 'skin', 'butcher', 'Gleaming golden apron for terrifying style.', 1000, true),
('skin_pig_muddy', 'Mud-Caked Pig', 'skin', 'pig', 'Maximum camouflage for muddy encounters.', 150, false),
('trail_feathers', 'Feather Flurry', 'trail', 'chicken', 'Leaves fluttering white feathers in your sprint wake.', 300, false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.bot_config (id, difficulty, reaction_delay_ms, wander_radius, flee_distance, stealth_affinity, is_active) VALUES
('bot_wanderer', 'easy', 400, 180.0, 200.0, 0.3, true),
('bot_skittish', 'normal', 280, 140.0, 260.0, 0.7, true),
('bot_herd_pig', 'normal', 300, 160.0, 220.0, 0.5, true)
ON CONFLICT (id) DO NOTHING;
